title: Warmhug
author: warmhug
email: hualei5280@gmail.com
github: https://github.com/warmhug

head_inline: "<style>td:first-child { width: 7rem; }</style>"

port: 4000
baseurl: /
url: http://localhost:4000

source: .
destination: ./_site
include: ["__*md"]

markdown: kramdown
# highlighter: 'pygments'
paginate: 15
paginate_path: "/page:num/"

collections:
  collections:
    output: true

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
