title: Warmhug
author: warmhug
email: hualei5280@gmail.com
description: >
  成长 | 感悟 | 反思

head_inline: "<style>td:first-child { width: 7rem; }</style>"

safe: true
jekyll serve: true
port: 4000
baseurl: /
url: http://localhost:4000

source: .
destination: ./_site
lsi: false

markdown: kramdown
# highlighter: 'pygments'

collections:
  collections:
    output: true

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
